name: PR Build and Test 🧑‍🔧

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.git**'

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: build test
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
        id: gradle

      - name: "Comment build scan url"
        uses: actions/github-script@v4.0.2
        if: ${{ failure() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ ${{ github.workflow }} failed: ${{ steps.gradle.outputs.build-scan-url }}'
            })

      - uses: actions/upload-artifact@v2
        with:
          path: build/libs/CurseForge2Discord.jar
          if-no-files-found: error
