name: Release Workflow
on:
  push:
    paths-ignore:
    - '**.md'
    - '.git**'
    branches-ignore:
    - 'dependabot/**'
  create:
    tags:
      - v*
jobs:
  release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-curse2discord

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: CurseForge2DiscordExcecutable
          path: ./build/libs/CurseForge2Discord.jar

      - name: Create release
        id: create_release
        if: github.event_name == 'create'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: CurseForge2Discord ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release
        if: github.event_name == 'create'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/CurseForge2Discord.jar
          asset_name: CurseForge2Discord.jar
          asset_content_type: application/jar

      - name: Publish to DockerHub
        if: github.event_name == 'create'
        uses: elgohr/Publish-Docker-Github-Action@3.02
        with:
          name: ijo42/curseforge2discord
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true

      - name: Publish to DockerHub
        if: github.event_name == 'push'
        uses: elgohr/Publish-Docker-Github-Action@3.02
        with:
          name: ijo42/curseforge2discord
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
